version: '3.6'

services:
  app:
    build:
      context: docker/build/app
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    tty: true
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html:delegated
      - /var/www/html/develop
